name: argenius
description: Library for parsing commandline arguments and using then with global scope or parse string commands on any other time
version: 1.1.1
homepage: https://paveltretyakovru.github.io/argenius/
repository: https://github.com/paveltretyakovru/argenius.git

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
